# Bash completions via Homebrew.
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && \
    . "/opt/homebrew/etc/profile.d/bash_completion.sh"

export CLICOLOR=1
HISTSIZE=10000
HISTFILESIZE=10000

export PATH=/opt/homebrew/bin:/usr/local/bin:/usr/local/sbin:/opt/homebrew/opt/node@20/bin:$PATH:$HOME/Scripts

# Better prompt, with color.
export PS1="\u@\h: \[\033[0;34m\]\w \[\033[00m\]\$ "
