export PATH=/opt/homebrew/bin:/usr/local/bin:/usr/local/sbin:$PATH:$HOME/Scripts

# Tab completions.
FPATH=$(brew --prefix)/share/zsh/zsh-completions:$FPATH
autoload -Uz compinit && compinit

# Ensure zsh path expansion behaves more like bash,
# which adds a forward slash to paths.
setopt no_auto_remove_slash

# Color output for ls and other tools.
export CLICOLOR=1
alias diff="diff --color"

# Better history handling.
HISTSIZE=10000
HISTFILESIZE=10000
SAVEHIST=$HISTSIZE
alias history="history 1"

# Setup git PS1 helpers.
# These bash completions work on zsh too.
source /opt/homebrew/etc/bash_completion.d/git-prompt.sh
export GIT_PS1_SHOWCOLORHINTS=true
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1

export VIRTUAL_ENV_DISABLE_PROMPT=1
venv_prompt() {
    if [[ -n "$VIRTUAL_ENV" ]]; then
        echo "($(python --version)) "
    else
        echo ""
    fi
}

precmd() {
    PS1="%F{magenta}$(venv_prompt)%F{blue}%n%F{reset}@%F{green}%m%F{reset}: %F{blue}%~%F{reset}$(__git_ps1)%F{magenta} $%F{reset} "
}
