export CLICOLOR=1
export PATH=/usr/local/opt/node@14/bin:/usr/local/bin:/usr/local/sbin:$PATH:$HOME/Scripts
export PYTHONSTARTUP=$HOME/.pystartup

# Homebrew tab expansion.
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# Java development
export JAVA_HOME=$(/usr/libexec/java_home)

# zsh improvments
alias history="history 1"

# Better prompt, with color.
export PS1="%n@%m:%F{green}$AWS_PROFILE %F{blue}%1~%F{reset} %# "

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform
